// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FSISSystem.Entities;

public partial class Game
{
    [Key]
    public int GameID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime GameDate { get; set; }

    public int HomeTeamID { get; set; }

    public int VisitingTeamID { get; set; }

    public int HomeTeamScore { get; set; }

    public int VisitingTeamScore { get; set; }

    [ForeignKey("HomeTeamID")]
    [InverseProperty("GameHomeTeams")]
    public virtual Team HomeTeam { get; set; }

    [InverseProperty("Game")]
    public virtual ICollection<PlayerStat> PlayerStats { get; set; } = new List<PlayerStat>();

    [ForeignKey("VisitingTeamID")]
    [InverseProperty("GameVisitingTeams")]
    public virtual Team VisitingTeam { get; set; }
}