// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FSISSystem.Entities;

public partial class Guardian
{
    [Key]
    public int GuardianID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string EmergencyPhoneNumber { get; set; }

    [Required]
    [StringLength(75)]
    [Unicode(false)]
    public string EmailAddress { get; set; }

    [InverseProperty("Guardian")]
    public virtual ICollection<Player> Players { get; set; } = new List<Player>();
}