// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FSISSystem.Entities;

public partial class PlayerStat
{
    [Key]
    public int PlayerStatsID { get; set; }

    public int GameID { get; set; }

    public int PlayerID { get; set; }

    public int Goals { get; set; }

    public int Assists { get; set; }

    public bool YellowCard { get; set; }

    public bool RedCard { get; set; }

    [ForeignKey("GameID")]
    [InverseProperty("PlayerStats")]
    public virtual Game Game { get; set; }

    [ForeignKey("PlayerID")]
    [InverseProperty("PlayerStats")]
    public virtual Player Player { get; set; }
}